#!/usr/bin/env bash
# Date: 25-12-25
# Author: omitida
# Description:
# Bash script for making and running zig-lang files.
#
#
function avaliable_option() {
    echo
    echo "Usage: ${0} <-option> <filename>"
    echo "Avaliable Option"
    echo "================"
    echo "-b:   Build a zig file."
    echo "-c:   Compile a zig file and run a compile file."
    echo "-d    Delete the specified folder or file"
    echo "-g:   Make a generic zig file."
    echo "-h:   Display this help function and options."
    echo "-p    Building Zig Project, with zig file structure."
    echo "-r:   Run a compile file."
    echo "-t:   Test a zig file."
}

#global name filename
filename=

function check_extention() {
    filename="${1}"
    extention="${filename#*.}"
    [[ "$extention" != "zig" ]] && filename="${filename%.*}.zig"
}

function create_zig_file() {
    filename="${1}"
    check_extention "${filename}"
    file_to_write="
    const std = @import(\"std\");

    pub fn main() void {
        std.debug.print(\"Start from here!\\n\", .{});
    }
    "
    if [[ -e "${filename}" ]]; then
        while read -p "${filename} exist. Do you want to overwrite it? [Y|N]: " ans; do
            case "${ans,,}" in
                y)
                    echo "${file_to_write}" > "${filename}"
                    echo "${filename} overwriten!"
                    exit 0
                    ;;
                n)
                    echo "${filename}. Not changed!"
                    exit 0
                    ;;
                *)
                    echo "Invalid input use only Y and N"
            esac
       done
    else
        echo "${file_to_write}" > "${filename}"
    fi
    [[ -z "${filename}" ]] && echo "${file_to_write}" > "${filename}"

    # format zif file
    zig fmt "${filename}"
}

if [[ "${#}" -ne 2 ]]; then
   avaliable_option
   exit 1
fi

opstring="b:c:d:g:r:t:p:h"

while getopts "${opstring}" opt; do
    case "${opt}" in
        b)
            filename="${OPTARG}"
            check_extention "${filename}"

            zig build-exe "${filename}"
            compile_file="${filename%.*}"
            ./"${compile_file}"

            rm "${compile_file}"
            ;;
        c)
            filename="${OPTARG}"
            create_zig_file "${filename}"
            ;;
        d)
            filename="${OPTARG}"
            if [[ -d "${filename}" ]]; then
                rmdir "${filename}"
                exit 0
            fi
            rm "${filename}"
            echo "${filename} Deleted Successfully."
            ;;
        g)
            filename="${OPTARG}"
            ${0} -r "${filename}"

            ;;
        r)
            filename="${OPTARG}"
            check_extention "${filename}"

           if  [[ -e "${filename}" ]]; then
               zig run "${filename}"
               exit 0
           else
               ${0} -c "${filename}"
               zig run "${filename}"
            fi
            ;;
        p)
            # project file in zig-lang
            filename="${OPTARG}"

            ! [[ -e "${filename}" ]] && mkdir "${filename}"

            if ! [[ -d "${filename}" ]]; then
                echo "The filename must be a Directory!"
                exit 1
            fi

            cd "${filename}"

            zig init # initialize the project
            zig build
            ./zig-out/bin/"${filename%.*}"
            zig build test
            ;;

        t)
            filename="${OPTARG}"
            zig test "${filename}"

            ;;
        h)
            avaliable_option
            ;;
        *)
    esac
done
